### ISSUE TITLE
Truncate Number Control does not support read-only mode

### ISSUE THREAD

**Issue by sgtsnacks-64** [cathalnoonan/d365-pcf-truncatednumber#19]
### Description

We're using the latest version of this control and previously, it appeared to support being in read-only state via the entity form. However as per the latest release, this control allows for user input even when "read-only" is set.

### Steps to reproduce

1. Add control to form
2. Set field to "read-only"
3. Observe behaviour of field in active form.

### Screenshots

![image](https://github.com/cathalnoonan/d365-pcf-truncatednumber/assets/96265020/e706b8a4-9cfe-41f9-b825-4b6836536a2b)

![image](https://github.com/cathalnoonan/d365-pcf-truncatednumber/assets/96265020/82328140-212c-432b-a346-fd41e4f8e5ad)

### Version installed

v1.1.3

**Comment by cathalnoonan** [comment]
Hi @sgtsnacks-64 

[v1.2.0](https://github.com/cathalnoonan/d365-pcf-truncatednumber/releases/tag/v1.2.0) has the fix included.
